<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Enable foreign key checks
        \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
                
        // Clear existing companies
        DB::table('jb_companies')->truncate();
                
        // Sample companies/recruiters data matching actual table structure
        $companies = [
            [
                'name' => 'Tech Innovations Inc.',
                'email' => 'careers@techinnovations.com',
                'description' => 'Leading technology company specializing in innovative solutions',
                'content' => '<p>Tech Innovations Inc. is a cutting-edge technology company focused on developing revolutionary software solutions for businesses worldwide. We specialize in AI, machine learning, and cloud computing technologies.</p>',
                'website' => 'https://techinnovations.com',
                'logo' => 'storage/companies/tech-logo.png',
                'latitude' => '37.7749',
                'longitude' => '-122.4194',
                'address' => '123 Tech Street, Silicon Valley, CA',
                'country_id' => 1,
                'state_id' => 1,
                'city_id' => 1,
                'postal_code' => '94102',
                'phone' => '+1 (555) 123-4567',
                'year_founded' => 2010,
                'ceo' => 'John Smith',
                'number_of_offices' => 5,
                'number_of_employees' => '500-1000',
                'annual_revenue' => '$50M-$100M',
                'cover_image' => 'storage/companies/tech-banner.jpg',
                'facebook' => 'techinnovations',
                'twitter' => 'techinnovations',
                'linkedin' => 'company/tech-innovations-inc',
                'instagram' => 'techinnovations',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-TECH-001',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Global Solutions Ltd.',
                'email' => 'jobs@globalsolutions.com',
                'description' => 'International consulting firm with global presence',
                'content' => '<p>Global Solutions Ltd. provides comprehensive consulting services across multiple industries including finance, healthcare, and technology. With offices in 20+ countries, we help businesses transform and grow.</p>',
                'website' => 'https://globalsolutions.com',
                'logo' => 'storage/companies/global-logo.png',
                'latitude' => '40.7128',
                'longitude' => '-74.0060',
                'address' => '456 Business Ave, New York, NY',
                'country_id' => 1,
                'state_id' => 2,
                'city_id' => 2,
                'postal_code' => '10001',
                'phone' => '+1 (555) 987-6543',
                'year_founded' => 2005,
                'ceo' => 'Sarah Johnson',
                'number_of_offices' => 25,
                'number_of_employees' => '1000-5000',
                'annual_revenue' => '$100M-$500M',
                'cover_image' => 'storage/companies/global-banner.jpg',
                'facebook' => 'globalsolutionsltd',
                'twitter' => 'globalsolutions',
                'linkedin' => 'company/global-solutions-ltd',
                'instagram' => 'globalsolutions',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-GLOBAL-002',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Creative Design Studio',
                'email' => 'careers@creativedesign.com',
                'description' => 'Award-winning creative agency specializing in digital design',
                'content' => '<p>Creative Design Studio is an award-winning digital agency that creates stunning visual experiences for brands worldwide. Our team of designers, developers, and strategists work together to deliver exceptional results.</p>',
                'website' => 'https://creativedesign.com',
                'logo' => 'storage/companies/creative-logo.png',
                'latitude' => '34.0522',
                'longitude' => '-118.2437',
                'address' => '789 Art District, Los Angeles, CA',
                'country_id' => 1,
                'state_id' => 1,
                'city_id' => 3,
                'postal_code' => '90015',
                'phone' => '+1 (555) 456-7890',
                'year_founded' => 2012,
                'ceo' => 'Michael Chen',
                'number_of_offices' => 3,
                'number_of_employees' => '100-500',
                'annual_revenue' => '$10M-$50M',
                'cover_image' => 'storage/companies/creative-banner.jpg',
                'facebook' => 'creativedesignstudio',
                'twitter' => 'creativestudio',
                'linkedin' => 'company/creative-design-studio',
                'instagram' => 'creativedesign',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-CREATIVE-003',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Finance Partners LLC',
                'email' => 'recruiting@financepartners.com',
                'description' => 'Financial services company with expertise in investment banking',
                'content' => '<p>Finance Partners LLC is a leading financial services firm specializing in investment banking, asset management, and corporate finance. We serve institutional clients globally with tailored financial solutions.</p>',
                'website' => 'https://financepartners.com',
                'logo' => 'storage/companies/finance-logo.png',
                'latitude' => '40.7128',
                'longitude' => '-74.0060',
                'address' => '321 Wall Street, New York, NY',
                'country_id' => 1,
                'state_id' => 2,
                'city_id' => 2,
                'postal_code' => '10005',
                'phone' => '+1 (555) 321-0987',
                'year_founded' => 2008,
                'ceo' => 'Robert Williams',
                'number_of_offices' => 8,
                'number_of_employees' => '500-1000',
                'annual_revenue' => '$50M-$100M',
                'cover_image' => 'storage/companies/finance-banner.jpg',
                'facebook' => 'financepartnersllc',
                'twitter' => 'financepartners',
                'linkedin' => 'company/finance-partners-llc',
                'instagram' => 'financepartners',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-FINANCE-004',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HealthTech Medical Systems',
                'email' => 'hr@healthtechmedical.com',
                'description' => 'Medical technology company developing healthcare solutions',
                'content' => '<p>HealthTech Medical Systems develops innovative medical technology solutions that improve patient care and healthcare outcomes. Our products are used in hospitals and clinics worldwide.</p>',
                'website' => 'https://healthtechmedical.com',
                'logo' => 'storage/companies/healthtech-logo.png',
                'latitude' => '42.3601',
                'longitude' => '-71.0589',
                'address' => '654 Medical Drive, Boston, MA',
                'country_id' => 1,
                'state_id' => 3,
                'city_id' => 4,
                'postal_code' => '02108',
                'phone' => '+1 (555) 654-3210',
                'year_founded' => 2015,
                'ceo' => 'Dr. Emily Davis',
                'number_of_offices' => 6,
                'number_of_employees' => '200-500',
                'annual_revenue' => '$25M-$50M',
                'cover_image' => 'storage/companies/healthtech-banner.jpg',
                'facebook' => 'healthtechmedical',
                'twitter' => 'healthtechmed',
                'linkedin' => 'company/healthtech-medical-systems',
                'instagram' => 'healthtechmedical',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-HEALTH-005',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ondo',
                'email' => 'contact@ondo.com',
                'description' => 'Global technology company focusing on innovative solutions for enterprise clients',
                'content' => '<p>Ondo is a technology leader providing cutting-edge solutions to enterprise clients worldwide. We specialize in cloud infrastructure, data analytics, and AI-powered platforms.</p>',
                'website' => 'https://ondo.com',
                'logo' => 'storage/companies/ondo-logo.png',
                'latitude' => '52.3676',
                'longitude' => '4.9041',
                'address' => 'Amsterdam, Netherlands',
                'country_id' => 1,
                'state_id' => 4,
                'city_id' => 5,
                'postal_code' => '1012',
                'phone' => '+31 20 123 4567',
                'year_founded' => 2018,
                'ceo' => 'David Brown',
                'number_of_offices' => 12,
                'number_of_employees' => '1000-5000',
                'annual_revenue' => '$200M-$500M',
                'cover_image' => 'storage/companies/ondo-banner.jpg',
                'facebook' => 'ondo',
                'twitter' => 'ondo',
                'linkedin' => 'company/ondo',
                'instagram' => 'ondo',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-ONDO-006',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Square',
                'email' => 'jobs@square.com',
                'description' => 'Financial services and mobile payment company',
                'content' => '<p>Square provides business and financial tools for small and medium-sized businesses. Our platform includes payment processing, point-of-sale solutions, and business management tools.</p>',
                'website' => 'https://square.com',
                'logo' => 'storage/companies/square-logo.png',
                'latitude' => '40.7589',
                'longitude' => '-73.9851',
                'address' => 'New York, US',
                'country_id' => 1,
                'state_id' => 2,
                'city_id' => 6,
                'postal_code' => '10036',
                'phone' => '+1 (212) 792-4000',
                'year_founded' => 2009,
                'ceo' => 'Jack Dorsey',
                'number_of_offices' => 18,
                'number_of_employees' => '5000-10000',
                'annual_revenue' => '$1B-$5B',
                'cover_image' => 'storage/companies/square-banner.jpg',
                'facebook' => 'square',
                'twitter' => 'square',
                'linkedin' => 'company/square',
                'instagram' => 'square',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-SQUARE-007',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nintendo',
                'email' => 'careers@nintendo.com',
                'description' => 'Japanese multinational consumer electronics and video game company',
                'content' => '<p>Nintendo is a world-renowned entertainment company creating innovative video games and interactive experiences. We develop hardware and software for home and portable gaming systems.</p>',
                'website' => 'https://nintendo.com',
                'logo' => 'storage/companies/nintendo-logo.png',
                'latitude' => '34.6937',
                'longitude' => '135.5023',
                'address' => 'Kyoto, Japan',
                'country_id' => 1,
                'state_id' => 5,
                'city_id' => 7,
                'postal_code' => '601-8501',
                'phone' => '+81 75 221 9393',
                'year_founded' => 1889,
                'ceo' => 'Shuntaro Furukawa',
                'number_of_offices' => 20,
                'number_of_employees' => '5000-10000',
                'annual_revenue' => '$5B-$10B',
                'cover_image' => 'storage/companies/nintendo-banner.jpg',
                'facebook' => 'nintendo',
                'twitter' => 'nintendo',
                'linkedin' => 'company/nintendo',
                'instagram' => 'nintendo',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-NINTENDO-008',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bing Search',
                'email' => 'jobs@bing.com',
                'description' => 'Web search engine developed by Microsoft',
                'content' => '<p>Bing is a search engine that provides a wide range of search services, including web, images, videos, maps, and news. We offer advanced search capabilities and integrated services.</p>',
                'website' => 'https://bing.com',
                'logo' => 'storage/companies/bing-logo.png',
                'latitude' => '47.6062',
                'longitude' => '-122.3321',
                'address' => 'Redmond, WA, US',
                'country_id' => 1,
                'state_id' => 6,
                'city_id' => 8,
                'postal_code' => '98052',
                'phone' => '+1 (425) 882-8080',
                'year_founded' => 2009,
                'ceo' => 'Satya Nadella',
                'number_of_offices' => 15,
                'number_of_employees' => '10000+',
                'annual_revenue' => '$10B+$',
                'cover_image' => 'storage/companies/bing-banner.jpg',
                'facebook' => 'bing',
                'twitter' => 'bing',
                'linkedin' => 'company/bing',
                'instagram' => 'bing',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-BING-009',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toyota',
                'email' => 'careers@toyota.com',
                'description' => 'Japanese multinational automotive manufacturer',
                'content' => '<p>Toyota is a leading global automotive manufacturer known for quality, reliability, and innovation. We produce cars, trucks, SUVs, and hybrid vehicles with advanced technology.</p>',
                'website' => 'https://toyota.com',
                'logo' => 'storage/companies/toyota-logo.png',
                'latitude' => '35.2546',
                'longitude' => '136.9324',
                'address' => 'Toyota City, Japan',
                'country_id' => 1,
                'state_id' => 5,
                'city_id' => 9,
                'postal_code' => '471-8511',
                'phone' => '+81 561 72-5511',
                'year_founded' => 1937,
                'ceo' => 'Akio Toyoda',
                'number_of_offices' => 50,
                'number_of_employees' => '300000+',
                'annual_revenue' => '$250B+$',
                'cover_image' => 'storage/companies/toyota-banner.jpg',
                'facebook' => 'toyota',
                'twitter' => 'toyota',
                'linkedin' => 'company/toyota',
                'instagram' => 'toyota',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-TOYOTA-010',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Greenwood',
                'email' => 'info@greenwood.com',
                'description' => 'Innovative financial technology company',
                'content' => '<p>Greenwood is a fintech company focused on creating financial products and services for underrepresented communities. We provide banking, credit, and investment solutions.</p>',
                'website' => 'https://greenwood.com',
                'logo' => 'storage/companies/greenwood-logo.png',
                'latitude' => '40.7128',
                'longitude' => '-74.0060',
                'address' => 'New York, NY, US',
                'country_id' => 1,
                'state_id' => 2,
                'city_id' => 2,
                'postal_code' => '10004',
                'phone' => '+1 (929) 226-8226',
                'year_founded' => 2020,
                'ceo' => 'Vivek Garipalli',
                'number_of_offices' => 3,
                'number_of_employees' => '50-100',
                'annual_revenue' => '$10M-$50M',
                'cover_image' => 'storage/companies/greenwood-banner.jpg',
                'facebook' => 'greenwood',
                'twitter' => 'greenwood',
                'linkedin' => 'company/greenwood',
                'instagram' => 'greenwood',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-GREENWOOD-011',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Periscope',
                'email' => 'contact@periscope.com',
                'description' => 'Live streaming platform for video broadcasting',
                'content' => '<p>Periscope is a live video streaming app that allows users to broadcast real-time video to followers. We enable creators and brands to engage with audiences instantly.</p>',
                'website' => 'https://periscope.com',
                'logo' => 'storage/companies/periscope-logo.png',
                'latitude' => '37.7749',
                'longitude' => '-122.4194',
                'address' => 'San Francisco, CA, US',
                'country_id' => 1,
                'state_id' => 1,
                'city_id' => 10,
                'postal_code' => '94105',
                'phone' => '+1 (415) 222-3333',
                'year_founded' => 2015,
                'ceo' => 'Kayvon Beykpour',
                'number_of_offices' => 2,
                'number_of_employees' => '50-100',
                'annual_revenue' => '$5M-$10M',
                'cover_image' => 'storage/companies/periscope-banner.jpg',
                'facebook' => 'periscope',
                'twitter' => 'periscope',
                'linkedin' => 'company/periscope',
                'instagram' => 'periscope',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-PERISCOPE-012',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PowerHome',
                'email' => 'careers@powerhome.com',
                'description' => 'Technology-enabled home services company',
                'content' => '<p>PowerHome is a leading home services company providing HVAC, electrical, plumbing, and other residential services. We use technology to enhance customer experience and operational efficiency.</p>',
                'website' => 'https://powerhome.com',
                'logo' => 'storage/companies/powerhome-logo.png',
                'latitude' => '36.1627',
                'longitude' => '-86.7816',
                'address' => 'Franklin, TN, US',
                'country_id' => 1,
                'state_id' => 7,
                'city_id' => 11,
                'postal_code' => '37067',
                'phone' => '+1 (833) 336-0888',
                'year_founded' => 2014,
                'ceo' => 'Brad Griffith',
                'number_of_offices' => 150,
                'number_of_employees' => '10000+',
                'annual_revenue' => '$500M-$1B',
                'cover_image' => 'storage/companies/powerhome-banner.jpg',
                'facebook' => 'powerhome',
                'twitter' => 'powerhome',
                'linkedin' => 'company/powerhome',
                'instagram' => 'powerhome',
                'is_featured' => 1,
                'status' => 'published',
                'views' => rand(100, 1000),
                'tax_id' => 'TAX-POWERHOME-013',
                'unique_id' => uniqid('COMP_'),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        // Insert companies into database
        DB::table('jb_companies')->insert($companies);
        
        // Re-enable foreign key checks
        \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();
        
        echo "Sample companies seeded successfully!\n";
    }
}